// Comprehensive Afrikaans vocabulary database
const vocabularyDatabase = {
    beginner: [
        { afrikaans: "hond", english: "dog", example: "Die hond is groot." },
        { afrikaans: "kat", english: "cat", example: "Die kat is klein." },
        { afrikaans: "huis", english: "house", example: "Ons huis is wit." },
        { afrikaans: "water", english: "water", example: "Ek drink water." },
        { afrikaans: "brood", english: "bread", example: "Die brood is vars." },
        { afrikaans: "melk", english: "milk", example: "Ek drink melk." },
        { afrikaans: "boom", english: "tree", example: "Die boom is hoog." },
        { afrikaans: "boek", english: "book", example: "Ek lees 'n boek." },
        { afrikaans: "tafel", english: "table", example: "Die tafel is groot." },
        { afrikaans: "stoel", english: "chair", example: "Sit op die stoel." },
        { afrikaans: "dag", english: "day", example: "Dit is 'n mooi dag." },
        { afrikaans: "nag", english: "night", example: "Goeie nag!" },
        { afrikaans: "son", english: "sun", example: "Die son skyn." },
        { afrikaans: "maan", english: "moon", example: "Die maan is vol." },
        { afrikaans: "ster", english: "star", example: "Die sterre skyn." },
        { afrikaans: "man", english: "man", example: "Die man is sterk." },
        { afrikaans: "vrou", english: "woman", example: "Die vrou is slim." },
        { afrikaans: "kind", english: "child", example: "Die kind speel." },
        { afrikaans: "seun", english: "boy", example: "Die seun hardloop." },
        { afrikaans: "meisie", english: "girl", example: "Die meisie sing." },
        { afrikaans: "ma", english: "mother", example: "My ma is lief." },
        { afrikaans: "pa", english: "father", example: "My pa werk." },
        { afrikaans: "broer", english: "brother", example: "My broer is jonk." },
        { afrikaans: "suster", english: "sister", example: "My suster is mooi." },
        { afrikaans: "oog", english: "eye", example: "Ek het blou oë." },
        { afrikaans: "oor", english: "ear", example: "Ek kan hoor." },
        { afrikaans: "neus", english: "nose", example: "My neus is klein." },
        { afrikaans: "mond", english: "mouth", example: "Ek praat met my mond." },
        { afrikaans: "hand", english: "hand", example: "Ek het twee hande." },
        { afrikaans: "voet", english: "foot", example: "My voet is seer." },
        { afrikaans: "kop", english: "head", example: "My kop is groot." },
        { afrikaans: "hart", english: "heart", example: "My hart klop." },
        { afrikaans: "een", english: "one", example: "Ek het een appel." },
        { afrikaans: "twee", english: "two", example: "Ek het twee honde." },
        { afrikaans: "drie", english: "three", example: "Daar is drie katte." },
        { afrikaans: "vier", english: "four", example: "Ek het vier boeke." },
        { afrikaans: "vyf", english: "five", example: "Vyf vingers per hand." },
        { afrikaans: "ses", english: "six", example: "Ek is ses jaar oud." },
        { afrikaans: "sewe", english: "seven", example: "Sewe dae per week." },
        { afrikaans: "agt", english: "eight", example: "Ek slaap agt ure." },
        { afrikaans: "nege", english: "nine", example: "Nege maande." },
        { afrikaans: "tien", english: "ten", example: "Ek het tien vingers." },
        { afrikaans: "rooi", english: "red", example: "Die appel is rooi." },
        { afrikaans: "blou", english: "blue", example: "Die lug is blou." },
        { afrikaans: "groen", english: "green", example: "Die gras is groen." },
        { afrikaans: "geel", english: "yellow", example: "Die son is geel." },
        { afrikaans: "swart", english: "black", example: "Die nag is swart." },
        { afrikaans: "wit", english: "white", example: "Die melk is wit." },
        { afrikaans: "pienk", english: "pink", example: "Die blom is pienk." },
        { afrikaans: "oranje", english: "orange", example: "Die oranje is oranje." },
        { afrikaans: "groot", english: "big", example: "Die huis is groot." },
        { afrikaans: "klein", english: "small", example: "Die muis is klein." },
        { afrikaans: "lang", english: "long", example: "Die pad is lang." },
        { afrikaans: "kort", english: "short", example: "Die pen is kort." },
        { afrikaans: "hoog", english: "high", example: "Die berg is hoog." },
        { afrikaans: "laag", english: "low", example: "Die tafel is laag." },
        { afrikaans: "warm", english: "warm", example: "Die weer is warm." },
        { afrikaans: "koud", english: "cold", example: "Die water is koud." },
        { afrikaans: "mooi", english: "beautiful", example: "Die dag is mooi." },
        { afrikaans: "lelik", english: "ugly", example: "Die weer is lelik." },
        { afrikaans: "goed", english: "good", example: "Dit is goed." },
        { afrikaans: "sleg", english: "bad", example: "Dit is sleg." },
        { afrikaans: "nuut", english: "new", example: "My boek is nuut." },
        { afrikaans: "oud", english: "old", example: "Die huis is oud." },
        { afrikaans: "jonk", english: "young", example: "Die kind is jonk." },
        { afrikaans: "sterk", english: "strong", example: "Die man is sterk." },
        { afrikaans: "swak", english: "weak", example: "Ek voel swak." },
        { afrikaans: "vinnig", english: "fast", example: "Die motor is vinnig." },
        { afrikaans: "stadig", english: "slow", example: "Die skilpad is stadig." },
        { afrikaans: "hard", english: "hard", example: "Die klip is hard." },
        { afrikaans: "sag", english: "soft", example: "Die kussing is sag." },
        { afrikaans: "ja", english: "yes", example: "Ja, dis reg." },
        { afrikaans: "nee", english: "no", example: "Nee, dit is verkeerd." },
        { afrikaans: "dankie", english: "thank you", example: "Dankie vir alles." },
        { afrikaans: "asseblief", english: "please", example: "Asseblief help my." },
        { afrikaans: "hallo", english: "hello", example: "Hallo, hoe gaan dit?" },
        { afrikaans: "totsiens", english: "goodbye", example: "Totsiens, sien jou later." },
        { afrikaans: "môre", english: "tomorrow", example: "Tot môre!" },
        { afrikaans: "gister", english: "yesterday", example: "Ek het gister gewerk." },
        { afrikaans: "vandag", english: "today", example: "Vandag is Maandag." },
        { afrikaans: "nou", english: "now", example: "Kom nou!" },
        { afrikaans: "later", english: "later", example: "Sien jou later." },
        { afrikaans: "altyd", english: "always", example: "Ek is altyd hier." },
        { afrikaans: "nooit", english: "never", example: "Ek is nooit laat nie." },
        { afrikaans: "hier", english: "here", example: "Kom hier!" },
        { afrikaans: "daar", english: "there", example: "Dit is daar." },
        { afrikaans: "waar", english: "where", example: "Waar is jy?" },
        { afrikaans: "wanneer", english: "when", example: "Wanneer kom jy?" },
        { afrikaans: "wie", english: "who", example: "Wie is jy?" },
        { afrikaans: "wat", english: "what", example: "Wat is dit?" },
        { afrikaans: "hoekom", english: "why", example: "Hoekom nie?" },
        { afrikaans: "hoe", english: "how", example: "Hoe gaan dit?" },
        { afrikaans: "ek", english: "I", example: "Ek is gelukkig." },
        { afrikaans: "jy", english: "you", example: "Jy is mooi." },
        { afrikaans: "hy", english: "he", example: "Hy is my broer." },
        { afrikaans: "sy", english: "she", example: "Sy is my suster." },
        { afrikaans: "ons", english: "we", example: "Ons is vriende." },
        { afrikaans: "julle", english: "you (plural)", example: "Julle is welkom." },
        { afrikaans: "hulle", english: "they", example: "Hulle is gelukkig." },
        { afrikaans: "my", english: "my", example: "Dit is my boek." },
        { afrikaans: "jou", english: "your", example: "Dit is jou huis." },
    ],
    intermediate: [
        { afrikaans: "skool", english: "school", example: "Ek gaan skool toe." },
        { afrikaans: "werk", english: "work", example: "Ek gaan werk toe." },
        { afrikaans: "motor", english: "car", example: "My motor is vinnig." },
        { afrikaans: "fiets", english: "bicycle", example: "Ek ry fiets." },
        { afrikaans: "vliegtuig", english: "airplane", example: "Die vliegtuig vlieg." },
        { afrikaans: "trein", english: "train", example: "Die trein is laat." },
        { afrikaans: "skip", english: "ship", example: "Die skip vaar." },
        { afrikaans: "bed", english: "bed", example: "Ek slaap in my bed." },
        { afrikaans: "venster", english: "window", example: "Maak die venster oop." },
        { afrikaans: "deur", english: "door", example: "Sluit die deur." },
        { afrikaans: "muur", english: "wall", example: "Die muur is wit." },
        { afrikaans: "vloer", english: "floor", example: "Die vloer is skoon." },
        { afrikaans: "dak", english: "roof", example: "Die dak lek." },
        { afrikaans: "tuin", english: "garden", example: "Die tuin is mooi." },
        { afrikaans: "blom", english: "flower", example: "Die blom ruik lekker." },
        { afrikaans: "gras", english: "grass", example: "Die gras is groen." },
        { afrikaans: "appel", english: "apple", example: "Die appel is soet." },
        { afrikaans: "piesang", english: "banana", example: "Ek eet 'n piesang." },
        { afrikaans: "lemoen", english: "orange", example: "Die lemoen is suur." },
        { afrikaans: "druiwe", english: "grapes", example: "Ek hou van druiwe." },
        { afrikaans: "kaas", english: "cheese", example: "Die kaas is lekker." },
        { afrikaans: "botter", english: "butter", example: "Smeer botter op die brood." },
        { afrikaans: "eier", english: "egg", example: "Ek eet 'n eier." },
        { afrikaans: "vleis", english: "meat", example: "Die vleis is gaar." },
        { afrikaans: "vis", english: "fish", example: "Ek eet vis." },
        { afrikaans: "hoender", english: "chicken", example: "Die hoender lê eiers." },
        { afrikaans: "bees", english: "cow", example: "Die bees gee melk." },
        { afrikaans: "perd", english: "horse", example: "Ek ry perd." },
        { afrikaans: "skaap", english: "sheep", example: "Die skaap is wit." },
        { afrikaans: "vark", english: "pig", example: "Die vark is vet." },
        { afrikaans: "voël", english: "bird", example: "Die voël sing." },
        { afrikaans: "vis", english: "fish", example: "Die vis swem." },
        { afrikaans: "slang", english: "snake", example: "Die slang is giftig." },
        { afrikaans: "leeu", english: "lion", example: "Die leeu is sterk." },
        { afrikaans: "olifant", english: "elephant", example: "Die olifant is groot." },
        { afrikaans: "tier", english: "tiger", example: "Die tier is gevaarlik." },
        { afrikaans: "beer", english: "bear", example: "Die beer is bruin." },
        { afrikaans: "wolf", english: "wolf", example: "Die wolf huil." },
        { afrikaans: "vos", english: "fox", example: "Die vos is slim." },
        { afrikaans: "haas", english: "rabbit", example: "Die haas hardloop." },
        { afrikaans: "muis", english: "mouse", example: "Die muis is klein." },
        { afrikaans: "rot", english: "rat", example: "Die rot is lelik." },
        { afrikaans: "eekoring", english: "squirrel", example: "Die eekoring klim." },
        { afrikaans: "aap", english: "monkey", example: "Die aap speel." },
        { afrikaans: "sebrа", english: "zebra", example: "Die sebra is gestreep." },
        { afrikaans: "kameel", english: "camel", example: "Die kameel drink min." },
        { afrikaans: "krokodil", english: "crocodile", example: "Die krokodil is gevaarlik." },
        { afrikaans: "seekoei", english: "hippopotamus", example: "Die seekoei is groot." },
        { afrikaans: "renoster", english: "rhinoceros", example: "Die renoster is sterk." },
        { afrikaans: "giraffe", english: "giraffe", example: "Die giraffe is hoog." },
        { afrikaans: "berg", english: "mountain", example: "Die berg is hoog." },
        { afrikaans: "rivier", english: "river", example: "Die rivier vloei." },
        { afrikaans: "see", english: "sea", example: "Die see is blou." },
        { afrikaans: "strand", english: "beach", example: "Ons gaan strand toe." },
        { afrikaans: "bos", english: "forest", example: "Die bos is dig." },
        { afrikaans: "woestyn", english: "desert", example: "Die woestyn is droog." },
        { afrikaans: "eiland", english: "island", example: "Die eiland is klein." },
        { afrikaans: "lug", english: "sky", example: "Die lug is blou." },
        { afrikaans: "wolk", english: "cloud", example: "Die wolke is wit." },
        { afrikaans: "reën", english: "rain", example: "Die reën val." },
        { afrikaans: "sneeu", english: "snow", example: "Die sneeu is wit." },
        { afrikaans: "wind", english: "wind", example: "Die wind waai." },
        { afrikaans: "storm", english: "storm", example: "Die storm kom." },
        { afrikaans: "donder", english: "thunder", example: "Die donder dreun." },
        { afrikaans: "weerlig", english: "lightning", example: "Die weerlig blink." },
        { afrikaans: "mis", english: "fog", example: "Die mis is dig." },
        { afrikaans: "ys", english: "ice", example: "Die ys is koud." },
        { afrikaans: "vuur", english: "fire", example: "Die vuur brand." },
        { afrikaans: "rook", english: "smoke", example: "Die rook styg." },
        { afrikaans: "as", english: "ash", example: "Die as is grys." },
        { afrikaans: "stof", english: "dust", example: "Die stof vlieg." },
        { afrikaans: "sand", english: "sand", example: "Die sand is warm." },
        { afrikaans: "klip", english: "stone", example: "Die klip is hard." },
        { afrikaans: "rots", english: "rock", example: "Die rots is groot." },
        { afrikaans: "metaal", english: "metal", example: "Die metaal is sterk." },
        { afrikaans: "goud", english: "gold", example: "Die goud is duur." },
        { afrikaans: "silwer", english: "silver", example: "Die silwer blink." },
        { afrikaans: "koper", english: "copper", example: "Die koper is bruin." },
        { afrikaans: "yster", english: "iron", example: "Die yster is swaar." },
        { afrikaans: "glas", english: "glass", example: "Die glas breek." },
        { afrikaans: "hout", english: "wood", example: "Die hout is hard." },
        { afrikaans: "papier", english: "paper", example: "Die papier is wit." },
        { afrikaans: "plastiek", english: "plastic", example: "Die plastiek is lig." },
        { afrikaans: "klere", english: "clothes", example: "My klere is skoon." },
        { afrikaans: "hemp", english: "shirt", example: "My hemp is blou." },
        { afrikaans: "broek", english: "pants", example: "My broek is swart." },
        { afrikaans: "rok", english: "dress", example: "Die rok is mooi." },
        { afrikaans: "jas", english: "jacket", example: "Die jas is warm." },
        { afrikaans: "skoene", english: "shoes", example: "My skoene is nuut." },
        { afrikaans: "kouse", english: "socks", example: "My kouse is warm." },
        { afrikaans: "hoed", english: "hat", example: "My hoed is groot." },
        { afrikaans: "bril", english: "glasses", example: "Ek dra 'n bril." },
        { afrikaans: "horlosie", english: "watch", example: "My horlosie is presies." },
        { afrikaans: "ring", english: "ring", example: "Die ring is mooi." },
        { afrikaans: "ketting", english: "necklace", example: "Die ketting is goud." },
        { afrikaans: "armband", english: "bracelet", example: "Die armband is silwer." },
        { afrikaans: "sakdoek", english: "handkerchief", example: "Die sakdoek is wit." },
        { afrikaans: "handsak", english: "handbag", example: "Die handsak is swart." },
    ],
    advanced: [
        { afrikaans: "gelukkig", english: "happy", example: "Ek is baie gelukkig." },
        { afrikaans: "hartseer", english: "sad", example: "Sy is hartseer." },
        { afrikaans: "kwaad", english: "angry", example: "Hy is kwaad." },
        { afrikaans: "bang", english: "afraid", example: "Die kind is bang." },
        { afrikaans: "opgewonde", english: "excited", example: "Ons is opgewonde." },
        { afrikaans: "moeg", english: "tired", example: "Ek is baie moeg." },
        { afrikaans: "honger", english: "hungry", example: "Ek is honger." },
        { afrikaans: "dors", english: "thirsty", example: "Ek is dors." },
        { afrikaans: "siek", english: "sick", example: "Hy is siek." },
        { afrikaans: "gesond", english: "healthy", example: "Sy is gesond." },
        { afrikaans: "slim", english: "clever", example: "Jy is slim." },
        { afrikaans: "dom", english: "stupid", example: "Dit is dom." },
        { afrikaans: "vriendelik", english: "friendly", example: "Hy is vriendelik." },
        { afrikaans: "onvriendelik", english: "unfriendly", example: "Sy is onvriendelik." },
        { afrikaans: "eerlik", english: "honest", example: "Hy is eerlik." },
        { afrikaans: "oneerlik", english: "dishonest", example: "Sy is oneerlik." },
        { afrikaans: "vrienskap", english: "friendship", example: "Ons het 'n goeie vrienskap." },
        { afrikaans: "liefde", english: "love", example: "Liefde is belangrik." },
        { afrikaans: "haat", english: "hate", example: "Haat is sleg." },
        { afrikaans: "vrede", english: "peace", example: "Ons wil vrede hê." },
        { afrikaans: "oorlog", english: "war", example: "Oorlog is verskriklik." },
        { afrikaans: "geloof", english: "faith", example: "Hy het geloof." },
        { afrikaans: "hoop", english: "hope", example: "Daar is altyd hoop." },
        { afrikaans: "vrees", english: "fear", example: "Vrees is 'n probleem." },
        { afrikaans: "moed", english: "courage", example: "Sy het moed." },
        { afrikaans: "wysheid", english: "wisdom", example: "Wysheid kom met ouderdom." },
        { afrikaans: "kennis", english: "knowledge", example: "Kennis is mag." },
        { afrikaans: "onderwys", english: "education", example: "Onderwys is belangrik." },
        { afrikaans: "onderwyser", english: "teacher", example: "Die onderwyser is goed." },
        { afrikaans: "student", english: "student", example: "Die student leer." },
        { afrikaans: "klas", english: "class", example: "Die klas is groot." },
        { afrikaans: "lesing", english: "lesson", example: "Die lesing is interessant." },
        { afrikaans: "toets", english: "test", example: "Die toets is moeilik." },
        { afrikaans: "eksamen", english: "exam", example: "Die eksamen is môre." },
        { afrikaans: "graad", english: "grade", example: "My graad is goed." },
        { afrikaans: "sertifikaat", english: "certificate", example: "Ek het 'n sertifikaat." },
        { afrikaans: "diploma", english: "diploma", example: "Sy het 'n diploma." },
        { afrikaans: "graad", english: "degree", example: "Hy het 'n graad." },
        { afrikaans: "universiteit", english: "university", example: "Ek gaan universiteit toe." },
        { afrikaans: "kollege", english: "college", example: "Sy is by die kollege." },
        { afrikaans: "biblioteek", english: "library", example: "Ek lees in die biblioteek." },
        { afrikaans: "museum", english: "museum", example: "Die museum is interessant." },
        { afrikaans: "teater", english: "theater", example: "Ons gaan teater toe." },
        { afrikaans: "bioskoop", english: "cinema", example: "Die bioskoop is vol." },
        { afrikaans: "restaurant", english: "restaurant", example: "Die restaurant is duur." },
        { afrikaans: "hotel", english: "hotel", example: "Die hotel is groot." },
        { afrikaans: "hospitaal", english: "hospital", example: "Hy is in die hospitaal." },
        { afrikaans: "dokter", english: "doctor", example: "Die dokter help my." },
        { afrikaans: "verpleegster", english: "nurse", example: "Die verpleegster is vriendelik." },
        { afrikaans: "medisyne", english: "medicine", example: "Die medisyne help." },
        { afrikaans: "pil", english: "pill", example: "Drink die pil." },
        { afrikaans: "inspuiting", english: "injection", example: "Die inspuiting is seer." },
        { afrikaans: "operasie", english: "operation", example: "Die operasie is suksesvol." },
        { afrikaans: "pyn", english: "pain", example: "Ek het pyn." },
        { afrikaans: "seerplek", english: "wound", example: "Die seerplek genees." },
        { afrikaans: "bloed", english: "blood", example: "Daar is bloed." },
        { afrikaans: "been", english: "bone", example: "My been is gebreek." },
        { afrikaans: "spier", english: "muscle", example: "My spier is seer." },
        { afrikaans: "vel", english: "skin", example: "My vel is sag." },
        { afrikaans: "hare", english: "hair", example: "My hare is lank." },
        { afrikaans: "tand", english: "tooth", example: "My tand is seer." },
        { afrikaans: "tong", english: "tongue", example: "My tong is rooi." },
        { afrikaans: "keel", english: "throat", example: "My keel is seer." },
        { afrikaans: "maag", english: "stomach", example: "My maag is vol." },
        { afrikaans: "lewer", english: "liver", example: "Die lewer is belangrik." },
        { afrikaans: "nier", english: "kidney", example: "Die nier filter." },
        { afrikaans: "long", english: "lung", example: "Die long asem." },
        { afrikaans: "brein", english: "brain", example: "Die brein dink." },
        { afrikaans: "senuweestelsel", english: "nervous system", example: "Die senuweestelsel is kompleks." },
        { afrikaans: "bloedsomloop", english: "circulation", example: "Die bloedsomloop is belangrik." },
        { afrikaans: "asemhaling", english: "breathing", example: "Die asemhaling is normaal." },
        { afrikaans: "spysvertering", english: "digestion", example: "Die spysvertering is goed." },
        { afrikaans: "geneeskunde", english: "medicine", example: "Geneeskunde is 'n wetenskap." },
        { afrikaans: "wetenskap", english: "science", example: "Wetenskap is interessant." },
        { afrikaans: "wiskunde", english: "mathematics", example: "Wiskunde is moeilik." },
        { afrikaans: "geskiedenis", english: "history", example: "Geskiedenis is belangrik." },
        { afrikaans: "geografie", english: "geography", example: "Geografie is nuttig." },
        { afrikaans: "biologie", english: "biology", example: "Biologie is die studie van lewe." },
        { afrikaans: "chemie", english: "chemistry", example: "Chemie is interessant." },
        { afrikaans: "fisika", english: "physics", example: "Fisika is moeilik." },
        { afrikaans: "tegnologie", english: "technology", example: "Tegnologie ontwikkel." },
        { afrikaans: "ingenieurswese", english: "engineering", example: "Ingenieurswese is nuttig." },
        { afrikaans: "argitektuur", english: "architecture", example: "Argitektuur is mooi." },
        { afrikaans: "kuns", english: "art", example: "Kuns is kreatief." },
        { afrikaans: "musiek", english: "music", example: "Musiek is mooi." },
        { afrikaans: "dans", english: "dance", example: "Dans is pret." },
        { afrikaans: "sport", english: "sport", example: "Sport is gesond." },
        { afrikaans: "sokker", english: "soccer", example: "Sokker is gewild." },
        { afrikaans: "rugby", english: "rugby", example: "Rugby is sterk." },
        { afrikaans: "krieket", english: "cricket", example: "Krieket is interessant." },
        { afrikaans: "tennis", english: "tennis", example: "Tennis is vinnig." },
        { afrikaans: "gholf", english: "golf", example: "Gholf is rustig." },
        { afrikaans: "swem", english: "swimming", example: "Swem is gesond." },
        { afrikaans: "hardloop", english: "running", example: "Hardloop is goed." },
        { afrikaans: "fietsry", english: "cycling", example: "Fietsry is pret." },
        { afrikaans: "bergklim", english: "mountain climbing", example: "Bergklim is gevaarlik." },
        { afrikaans: "duik", english: "diving", example: "Duik is opwindend." },
        { afrikaans: "surf", english: "surfing", example: "Surf is pret." },
    ]
};

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = vocabularyDatabase;
}
